language: node_js
node_js: 7
cache:
  yarn: true
  directories:
  - node_modules
  - "${NVM_PATH}_modules"
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- yarn
- cd functions && yarn && cd ..
script: echo "Deploying!"
before_deploy: yarn run build
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: hoverboard-master
  token:
    secure: X5+6sQAnRO/SYCffdhcGezdkAaJ+fqjZkkje8pDWAvxKuYk4JNpZFgD+fmH7KHTqJuWFAuhfDPq9BAhSDxt9Vnnvkyj41fzahzoBJfDWLnYbc3dUl1oCEAna/uijGXUZw5IkTdNkzTpm5t2DT3Yiw/LxJiH9ekSqCnfRb5p4RVh2hH6TsH9bqI78gHGPwO9U9gpd8n3jC/TEc/RiasVBzubIM+VQQAcYxkoYixv9Aom30D/EbrWXDWiEOgEntoePF+fO8lE+YmTEV2NVhHVmPwXF9L3sI+eR6wmV0fwKMbl2nJHbHgVdfPCUL/C40owwMOqb/QmNHkIn9bT6qIpjEGG36Jv2CI0+Sepp44TYWcqIV5yLgaHYR9EhxmdzWbVAS18yZy92ejgt6bHTR2m5GcTupolhFoO2UwdC1NNXnWU+kD5E+cLRT6nFwKcTBwLYPr5ULXekgco9HewhUrWrzuo0NTBV7Wwg/nY7j5i+c4GCubo5JLo/3vNvcowKlErqEy60q6gpwRKgxG3+jyp8pMVKn2Mk9ItPuf1zibyCz8UJC9tYa8DasJLnHzFKYRuCDVl7DA+cGRuBJL/y2zUqudxe14zmZcCVBY6eCuxwkS38E2wO1W0lTMWWjgz3FUAxlVCDOZErShoK4rJaQGXJ4Rj2msjE4UGlMmC87+p2aNs=
- provider: firebase
  skip_cleanup: true
  on:
    branch: develop
  project: hoverboard-dev
  token:
    secure: X5+6sQAnRO/SYCffdhcGezdkAaJ+fqjZkkje8pDWAvxKuYk4JNpZFgD+fmH7KHTqJuWFAuhfDPq9BAhSDxt9Vnnvkyj41fzahzoBJfDWLnYbc3dUl1oCEAna/uijGXUZw5IkTdNkzTpm5t2DT3Yiw/LxJiH9ekSqCnfRb5p4RVh2hH6TsH9bqI78gHGPwO9U9gpd8n3jC/TEc/RiasVBzubIM+VQQAcYxkoYixv9Aom30D/EbrWXDWiEOgEntoePF+fO8lE+YmTEV2NVhHVmPwXF9L3sI+eR6wmV0fwKMbl2nJHbHgVdfPCUL/C40owwMOqb/QmNHkIn9bT6qIpjEGG36Jv2CI0+Sepp44TYWcqIV5yLgaHYR9EhxmdzWbVAS18yZy92ejgt6bHTR2m5GcTupolhFoO2UwdC1NNXnWU+kD5E+cLRT6nFwKcTBwLYPr5ULXekgco9HewhUrWrzuo0NTBV7Wwg/nY7j5i+c4GCubo5JLo/3vNvcowKlErqEy60q6gpwRKgxG3+jyp8pMVKn2Mk9ItPuf1zibyCz8UJC9tYa8DasJLnHzFKYRuCDVl7DA+cGRuBJL/y2zUqudxe14zmZcCVBY6eCuxwkS38E2wO1W0lTMWWjgz3FUAxlVCDOZErShoK4rJaQGXJ4Rj2msjE4UGlMmC87+p2aNs=
- provider: firebase
  skip_cleanup: true
  on:
    branch: hoverboard-v2
  project: hoverboard-v2-dev
  token:
    secure: X5+6sQAnRO/SYCffdhcGezdkAaJ+fqjZkkje8pDWAvxKuYk4JNpZFgD+fmH7KHTqJuWFAuhfDPq9BAhSDxt9Vnnvkyj41fzahzoBJfDWLnYbc3dUl1oCEAna/uijGXUZw5IkTdNkzTpm5t2DT3Yiw/LxJiH9ekSqCnfRb5p4RVh2hH6TsH9bqI78gHGPwO9U9gpd8n3jC/TEc/RiasVBzubIM+VQQAcYxkoYixv9Aom30D/EbrWXDWiEOgEntoePF+fO8lE+YmTEV2NVhHVmPwXF9L3sI+eR6wmV0fwKMbl2nJHbHgVdfPCUL/C40owwMOqb/QmNHkIn9bT6qIpjEGG36Jv2CI0+Sepp44TYWcqIV5yLgaHYR9EhxmdzWbVAS18yZy92ejgt6bHTR2m5GcTupolhFoO2UwdC1NNXnWU+kD5E+cLRT6nFwKcTBwLYPr5ULXekgco9HewhUrWrzuo0NTBV7Wwg/nY7j5i+c4GCubo5JLo/3vNvcowKlErqEy60q6gpwRKgxG3+jyp8pMVKn2Mk9ItPuf1zibyCz8UJC9tYa8DasJLnHzFKYRuCDVl7DA+cGRuBJL/y2zUqudxe14zmZcCVBY6eCuxwkS38E2wO1W0lTMWWjgz3FUAxlVCDOZErShoK4rJaQGXJ4Rj2msjE4UGlMmC87+p2aNs=

